name: Docker build and test

on:
  push:
    branch:
      - testing-pipeline

jobs:
  build:
    runs-on: ubuntu-latest

  steps: 
    - name: checkout our repository
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: bulid the docker Iamge
      run: docker build -t shahosalih/service-web-store-lab4:shahosalih/service-web-store-lab4 .

    - name: log in to the ole docker hub
      run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

    - name: push the docker to that silly little dockerhub
      run: docker push shahosalih/service-web-store-lab4:shahosalih/service-web-store-lab4